
package uvpalivol.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.time.LocalDate;
import java.time.LocalTime;

import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataListener;
import javax.swing.table.AbstractTableModel;

import uvpavicol.clases.Empresa;
import uvpavicol.clases.Galpon;
import uvpavicol.clases.Lote;
import uvpavicol.clases.RegistroDiario;
import uvpavicol.clases.Salida;


public class GestionLotes extends javax.swing.JInternalFrame {
    private Empresa empresa;

    public GestionLotes(Empresa empresa) {
        
        this.empresa = empresa;  
        
        initComponents();
        
        
        btnDiario.addActionListener(new ManejadorRegistrosDiario());
        btnLote.addActionListener(new ManejadorRegistrosLotes());
        btnSalida.addActionListener(new ManejadorRegistrosSalidas());
        btnBorrar.addActionListener(new Borrar());
        btnBorrar1.addActionListener(new Borrar());
        btnBorrar2.addActionListener(new Borrar());
    
        boxGalponA.setModel(new GalponComboBoxModel(empresa));
        boxLotes.setModel(new LoteComboBoxModel(empresa));
        tblLotes.setModel(new LotesModelo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLotes = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tcfFechaRegistroDiario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txfIngreso = new javax.swing.JTextField();
        txfMuertes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txfPeso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnDiario = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txfIngreso1 = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txfFechaIngresoLote = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnLote = new javax.swing.JButton();
        boxGalponA = new javax.swing.JComboBox<>();
        btnBorrar1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txfSacrificios = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txfFechaAvesSacrificar = new javax.swing.JTextField();
        btnSalida = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        boxLotes = new javax.swing.JComboBox<>();
        btnBorrar2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));

        tblLotes.setBackground(new java.awt.Color(255, 102, 102));
        tblLotes.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        tblLotes.setForeground(new java.awt.Color(102, 0, 0));
        tblLotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLotes);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pollo Reducido máspng.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro Diario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI Symbol", 1, 24), new java.awt.Color(51, 0, 0))); // NOI18N
        jPanel2.setToolTipText("Registro Diario");

        tcfFechaRegistroDiario.setBackground(new java.awt.Color(255, 153, 153));
        tcfFechaRegistroDiario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tcfFechaRegistroDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcfFechaRegistroDiarioActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setText("Fecha:");

        jLabel2.setBackground(new java.awt.Color(255, 153, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 0));
        jLabel2.setText("Aves que Ingresan:");

        txfIngreso.setBackground(new java.awt.Color(255, 153, 153));
        txfIngreso.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txfIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfIngresoActionPerformed(evt);
            }
        });

        txfMuertes.setBackground(new java.awt.Color(255, 153, 153));
        txfMuertes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txfMuertes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfMuertesActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 153, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 0));
        jLabel3.setText("Aves que Mueren");

        txfPeso.setBackground(new java.awt.Color(255, 153, 153));
        txfPeso.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txfPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPesoActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 153, 153));
        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 0));
        jLabel4.setText("Peso Promedio:");

        btnDiario.setBackground(new java.awt.Color(255, 204, 204));
        btnDiario.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        btnDiario.setForeground(new java.awt.Color(51, 0, 0));
        btnDiario.setText("Agregar Registro");
        btnDiario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDiario.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiarioActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 153, 153));
        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 0));
        jLabel8.setText("Cantidad Alimento:");

        txfIngreso1.setBackground(new java.awt.Color(255, 153, 153));
        txfIngreso1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txfIngreso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfIngreso1ActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(255, 204, 204));
        btnBorrar.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(51, 0, 0));
        btnBorrar.setText("borrar");
        btnBorrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txfMuertes, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txfIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addGap(30, 30, 30))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(txfIngreso1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(10, 10, 10)
                                .addComponent(txfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tcfFechaRegistroDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tcfFechaRegistroDiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txfIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txfIngreso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txfMuertes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 190));

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lote", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI Symbol", 1, 24), new java.awt.Color(51, 0, 0))); // NOI18N
        jPanel5.setToolTipText("Registro Diario");

        txfFechaIngresoLote.setBackground(new java.awt.Color(255, 153, 153));
        txfFechaIngresoLote.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txfFechaIngresoLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfFechaIngresoLoteActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 153, 153));
        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText("Fecha ingreso:");

        jLabel6.setBackground(new java.awt.Color(255, 153, 153));
        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jLabel6.setText("Galpón:");

        btnLote.setBackground(new java.awt.Color(255, 204, 204));
        btnLote.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        btnLote.setForeground(new java.awt.Color(51, 0, 0));
        btnLote.setText("Registrar Lote");
        btnLote.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLote.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoteActionPerformed(evt);
            }
        });

        boxGalponA.setBackground(new java.awt.Color(255, 153, 153));
        boxGalponA.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnBorrar1.setBackground(new java.awt.Color(255, 204, 204));
        btnBorrar1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        btnBorrar1.setForeground(new java.awt.Color(51, 0, 0));
        btnBorrar1.setText("borrar");
        btnBorrar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrar1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnBorrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txfFechaIngresoLote, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(boxGalponA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLote, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txfFechaIngresoLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBorrar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(boxGalponA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLote, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 130));

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salida", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI Symbol", 1, 24), new java.awt.Color(51, 0, 0))); // NOI18N
        jPanel6.setToolTipText("Salida");

        txfSacrificios.setBackground(new java.awt.Color(255, 153, 153));
        txfSacrificios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txfSacrificios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSacrificiosActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 153, 153));
        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 0));
        jLabel9.setText("Aves a sacrificar");

        jLabel10.setBackground(new java.awt.Color(255, 153, 153));
        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 0));
        jLabel10.setText("Fecha");

        txfFechaAvesSacrificar.setBackground(new java.awt.Color(255, 153, 153));
        txfFechaAvesSacrificar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txfFechaAvesSacrificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfFechaAvesSacrificarActionPerformed(evt);
            }
        });

        btnSalida.setBackground(new java.awt.Color(255, 204, 204));
        btnSalida.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        btnSalida.setForeground(new java.awt.Color(51, 0, 0));
        btnSalida.setText("Confirmar Salida");
        btnSalida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalida.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 153, 153));
        jLabel12.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 0));
        jLabel12.setText("Lotes:");

        boxLotes.setBackground(new java.awt.Color(255, 153, 153));
        boxLotes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnBorrar2.setBackground(new java.awt.Color(255, 204, 204));
        btnBorrar2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        btnBorrar2.setForeground(new java.awt.Color(51, 0, 0));
        btnBorrar2.setText("borrar");
        btnBorrar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrar2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnBorrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txfSacrificios, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txfFechaAvesSacrificar))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boxLotes, 0, 150, Short.MAX_VALUE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txfSacrificios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txfFechaAvesSacrificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(boxLotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnBorrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 130));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tcfFechaRegistroDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcfFechaRegistroDiarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcfFechaRegistroDiarioActionPerformed

    private void txfIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfIngresoActionPerformed

    private void txfMuertesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfMuertesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfMuertesActionPerformed

    private void txfPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfPesoActionPerformed

    private void btnDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDiarioActionPerformed

    private void txfFechaIngresoLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfFechaIngresoLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfFechaIngresoLoteActionPerformed

    private void btnLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoteActionPerformed

    private void txfSacrificiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfSacrificiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfSacrificiosActionPerformed

    private void txfFechaAvesSacrificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfFechaAvesSacrificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfFechaAvesSacrificarActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void txfIngreso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfIngreso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfIngreso1ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrar1ActionPerformed

    private void btnBorrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrar2ActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<uvpavicol.clases.Galpon> boxGalponA;
    private javax.swing.JComboBox<uvpavicol.clases.Lote> boxLotes;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBorrar1;
    private javax.swing.JButton btnBorrar2;
    private javax.swing.JButton btnDiario;
    private javax.swing.JButton btnLote;
    private javax.swing.JButton btnSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLotes;
    private javax.swing.JTextField tcfFechaRegistroDiario;
    private javax.swing.JTextField txfFechaAvesSacrificar;
    private javax.swing.JTextField txfFechaIngresoLote;
    private javax.swing.JTextField txfIngreso;
    private javax.swing.JTextField txfIngreso1;
    private javax.swing.JTextField txfMuertes;
    private javax.swing.JTextField txfPeso;
    private javax.swing.JTextField txfSacrificios;
    // End of variables declaration//GEN-END:variables
    
    public class Borrar implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            txfFechaAvesSacrificar.setText("");
            txfFechaIngresoLote.setText("");
            txfIngreso.setText("");
            txfMuertes.setText("");
            txfPeso.setText("");
            txfSacrificios.setText("");
            
            boxGalponA.setSelectedItem(null);
            boxLotes.setSelectedItem(null);
        }
    }
    
    public class ManejadorRegistrosDiario implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            try {
            //Lote loteActual = (Lote) boxLotes.getSelectedItem();
            
            LocalDate fecha =  LocalDate.now();
            float cantidadAlimento = Float.parseFloat(txfIngreso.getText());
            long avesIngresadas = Long.parseLong(txfIngreso1.getText());
            int avesMuertas = Integer.parseInt(txfMuertes.getText());
            double pesoPromedio = Double.parseDouble(txfPeso.getText());

            RegistroDiario diario= new RegistroDiario(LocalDate.now(),cantidadAlimento,avesMuertas,pesoPromedio);
            
            int lotePrueba = 1;
            empresa.getLosLotes().get(lotePrueba).addRegistroDiario(diario);
            
            } catch (Exception exc) {
                JOptionPane.showMessageDialog(GestionLotes.this,exc.getMessage());
            }
        }
    }
    public class ManejadorRegistrosLotes implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                LocalDate fecha =  LocalDate.now();
                Galpon galpon = (Galpon) boxGalponA.getSelectedItem();
                
                Lote lote = new Lote(fecha, galpon,1,1);
                empresa.addLotes(lote);
                tblLotes.updateUI();
                JOptionPane.showMessageDialog(GestionLotes.this,"lote registrado"); 
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(GestionLotes.this,ex.getMessage());  
            }
            
        }
    }
    public class ManejadorRegistrosSalidas implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                long avesSacrificadas = Long.parseLong(txfSacrificios.getText());
                LocalDate fecha = LocalDate.now();
                LocalTime hora = LocalTime.now();
            
                Salida salida = new Salida(avesSacrificadas, fecha, hora);
                
                Lote lote = (Lote) boxLotes.getSelectedItem();
                
                lote.addSalidas(salida);
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(GestionLotes.this,ex.getMessage());  
            }
            
        }
    }
    
    public class GalponComboBoxModel implements ComboBoxModel<Galpon>{
        private Object selected= null;
        private Empresa empresa;
        
        public GalponComboBoxModel(Empresa empresa){
            this.empresa=empresa;
        }
        @Override
        public void setSelectedItem(Object item) {
            this.selected = item;//seleccionar item
        }
        @Override
        public int getSize() {
            String nombre = "prueba";
            return empresa.unaGranja(nombre).getLosGalpones().size();
        }
        @Override
        public Galpon getElementAt(int index) {
            String nombre = "prueba";
            return empresa.unaGranja(nombre).getLosGalpones().get(index);
        }
        @Override
        public Object getSelectedItem() {
            return this.selected;
        }
        @Override
        public void addListDataListener(ListDataListener l) {}
        @Override
        public void removeListDataListener(ListDataListener l) {}
        
    }
    public class LoteComboBoxModel implements ComboBoxModel<Lote>{
        private Object selected= null;// Objeto seleccionado en el JComboBox
        private Empresa empresa;
        
        //@Override
        public  LoteComboBoxModel(Empresa empresa) {
           this.empresa=empresa;//tipo objeto que recibe
        }
        
        @Override
        public void setSelectedItem(Object item) {
            this.selected = item;//seleccionar item
        }
        @Override
        public int getSize() {
            return empresa.getLosLotes().size();
        }
        @Override
        public Lote getElementAt(int index) {
            return empresa.getLosLotes().get(index);
        }
        @Override
        public Object getSelectedItem() {
            return this.selected;
        }
        @Override
        public void addListDataListener(ListDataListener l) {}
        @Override
        public void removeListDataListener(ListDataListener l) {}
        
        
    }
    
    public class LotesModelo extends AbstractTableModel{

        @Override
        public int getRowCount() {
            return empresa.getLosLotes().size();
        }

        @Override
        public int getColumnCount() {
            return 2;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Lote loteParaTabla = empresa.getLosLotes().get(rowIndex);
            switch (columnIndex) {
                case 0:return loteParaTabla.getFechaIngreso();
                case 1: return loteParaTabla.getGalpon().getIdentificador();
                
                default:
                    throw new AssertionError();
            }
        }
        @Override
        public String getColumnName(int column) {
            switch (column) {
                case 0:return "fecha ingreso";
                case 1:return " galpon";
            }
            return "reza pq nc, como se ejecutaria esto";
        
        }
    }
}

