/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package uvpalivol.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import uvpavicol.clases.Empresa;

/**
 *
 * @author yhonn mauricio lara
 */
public class PlantillaGestionLotes extends javax.swing.JInternalFrame {
    private Empresa empresa;
    /**
     * Creates new form PlantillaGestionLotes
     */
    public PlantillaGestionLotes(Empresa empresa) {
        this.empresa=empresa;
        initComponents();
        
        btnLote.addActionListener(new ManejadorNuevoLote());
        btnRegistroDiario.addActionListener(new ManejadorRegistroDiario());
        btnSalida.addActionListener(new ManejadorSalidas());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        btnLote = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        btnRegistroDiario = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();

        jPanel5.setBackground(new java.awt.Color(255, 102, 102));
        jPanel5.setDoubleBuffered(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLote.setBackground(new java.awt.Color(255, 102, 102));
        btnLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/building3.png"))); // NOI18N
        btnLote.setBorderPainted(false);
        btnLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLotebtnGstnGranjaActionPerformed(evt);
            }
        });
        jPanel5.add(btnLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 60, -1));

        btnSalida.setBackground(new java.awt.Color(255, 102, 102));
        btnSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/useredit.png"))); // NOI18N
        btnSalida.setBorderPainted(false);
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidabtnUsuarioActionPerformed(evt);
            }
        });
        jPanel5.add(btnSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 60, -1));

        btnRegistroDiario.setBackground(new java.awt.Color(255, 102, 102));
        btnRegistroDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gallina (1).png"))); // NOI18N
        btnRegistroDiario.setBorderPainted(false);
        btnRegistroDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroDiariojButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(btnRegistroDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 60, -1));

        jButton13.setBackground(new java.awt.Color(255, 102, 102));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Univalle.png"))); // NOI18N
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jPanel5.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));

        desktop.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pollo Navidad 2.png"))); // NOI18N

        desktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel1)
                .addContainerGap(260, Short.MAX_VALUE))
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel5.add(desktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 880, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLotebtnGstnGranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLotebtnGstnGranjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLotebtnGstnGranjaActionPerformed

    private void btnSalidabtnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidabtnUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalidabtnUsuarioActionPerformed

    private void btnRegistroDiariojButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroDiariojButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroDiariojButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLote;
    private javax.swing.JButton btnRegistroDiario;
    private javax.swing.JButton btnSalida;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

    public class ManejadorRegistroDiario implements ActionListener {
            private PlantillaGestionRegistroDiarios vtnGestionGranja = null;

        @Override
        public void actionPerformed(ActionEvent e) {
            if (this.vtnGestionGranja == null){
                vtnGestionGranja = new PlantillaGestionRegistroDiarios(empresa);
                desktop.add(vtnGestionGranja);
            }
            vtnGestionGranja.setVisible(true);
        }
        
    }

    public class ManejadorNuevoLote implements ActionListener {

        private PlantillaNuevoLote vtnGestionLotes = null;

        @Override
        public void actionPerformed(ActionEvent e) {
            if (this.vtnGestionLotes == null) {
                vtnGestionLotes = new  PlantillaNuevoLote (empresa);
                desktop.add(vtnGestionLotes);
            }
            vtnGestionLotes.setVisible(true);
        }

    }

    public class ManejadorSalidas implements ActionListener {

        private PlantillaGestionarSalidas vtnUsuarios = null;

        @Override
        public void actionPerformed(ActionEvent e) {
            if (this.vtnUsuarios == null) {
                vtnUsuarios = new PlantillaGestionarSalidas (empresa);
                desktop.add(vtnUsuarios);
            }
            vtnUsuarios.setVisible(true);

        }

    }
}
