/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package uvpalivol.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataListener;
import javax.swing.table.AbstractTableModel;
import uvpavicol.clases.Empresa;
import uvpavicol.clases.Galpon;
import javax.swing.JComboBox;
import uvpavicol.clases.Lote;
import uvpavicol.clases.RegistroDiario;
import uvpavicol.clases.Salida;
import uvpavicol.clases.TipoAlimento;

/**
 *
 * @author yhonn mauricio lara
 */
public class PlantillaGestionLotes extends javax.swing.JInternalFrame {
    private Empresa empresa;
    
    /**
     * Creates new form GestionRegistroDiarios
     */
    public PlantillaGestionLotes(Empresa empresa) {
        this.empresa=empresa;
        initComponents();
        
        btnGuardarDiario.addActionListener(new ManejadorRegistrosDiario());
        btnBorrarDiario.addActionListener(new ManejadorBorrarRegistroDiario());
        boxLotes.setModel(new LoteComboBoxModel(empresa));
        
        btnGuardarSalida.addActionListener(new ManejadorRegistrosSalidas());
        btnBorrarSalida.addActionListener(new ManejadorBorrarSalidas());
        boxLotesSalida.setModel(new LoteComboBoxModel(empresa));
        
        tblLotes.setModel(new LoteInfoModel());
        
        btnBorrarDiario.doClick();
        btnBorrarSalida.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txfCantidadAlimento = new javax.swing.JTextField();
        btnGuardarDiario = new javax.swing.JButton();
        btnBorrarDiario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        boxLotes = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txfMuertes = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txfPesoMedio = new javax.swing.JTextField();
        boxTipoAlimento = new JComboBox<>(TipoAlimento.values());
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLotes = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnGuardarSalida = new javax.swing.JButton();
        btnBorrarSalida = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        boxLotesSalida = new javax.swing.JComboBox<>();
        txfAvesSacrificar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        txfCantidadAlimento.setBackground(new java.awt.Color(255, 102, 102));
        txfCantidadAlimento.setBorder(null);
        txfCantidadAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCantidadAlimentoActionPerformed(evt);
            }
        });

        btnGuardarDiario.setBackground(new java.awt.Color(51, 0, 0));
        btnGuardarDiario.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnGuardarDiario.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarDiario.setText("Registro");
        btnGuardarDiario.setBorder(null);
        btnGuardarDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDiarioActionPerformed(evt);
            }
        });

        btnBorrarDiario.setBackground(new java.awt.Color(51, 0, 0));
        btnBorrarDiario.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnBorrarDiario.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarDiario.setText("Cancelar lote");
        btnBorrarDiario.setBorder(null);
        btnBorrarDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarDiarioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Número del lote");

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Tipo Alimento");

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Cant alimento");

        boxLotes.setBackground(new java.awt.Color(255, 102, 102));
        boxLotes.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro Diario");

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Muertes");

        txfMuertes.setBackground(new java.awt.Color(255, 102, 102));
        txfMuertes.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Peso Medio");

        txfPesoMedio.setBackground(new java.awt.Color(255, 102, 102));
        txfPesoMedio.setBorder(null);

        boxTipoAlimento.setBackground(new java.awt.Color(255, 102, 102));
        boxTipoAlimento.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnGuardarDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnBorrarDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfCantidadAlimento)
                            .addComponent(txfMuertes)
                            .addComponent(txfPesoMedio)
                            .addComponent(boxTipoAlimento, 0, 160, Short.MAX_VALUE)
                            .addComponent(boxLotes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxLotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxTipoAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfCantidadAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfMuertes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfPesoMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrarDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 460));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        tblLotes.setBackground(new java.awt.Color(255, 204, 204));
        tblLotes.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        tblLotes.setForeground(new java.awt.Color(51, 0, 0));
        tblLotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLotes);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pollo Reducido máspng.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 350, 460));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        btnGuardarSalida.setBackground(new java.awt.Color(51, 0, 0));
        btnGuardarSalida.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnGuardarSalida.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarSalida.setText("Registrar Salida");
        btnGuardarSalida.setBorder(null);
        btnGuardarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarSalidaActionPerformed(evt);
            }
        });

        btnBorrarSalida.setBackground(new java.awt.Color(51, 0, 0));
        btnBorrarSalida.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        btnBorrarSalida.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarSalida.setText("Cancelar Salida");
        btnBorrarSalida.setBorder(null);
        btnBorrarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarSalidaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Lote");

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Aves Sacrificadas");

        boxLotesSalida.setBackground(new java.awt.Color(255, 102, 102));
        boxLotesSalida.setBorder(null);

        txfAvesSacrificar.setBackground(new java.awt.Color(255, 102, 102));
        txfAvesSacrificar.setBorder(null);

        jLabel12.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Salida");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxLotesSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfAvesSacrificar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnGuardarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxLotesSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfAvesSacrificar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(204, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 330, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDiarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarDiarioActionPerformed

    private void btnBorrarDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarDiarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarDiarioActionPerformed

    private void btnGuardarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarSalidaActionPerformed

    private void btnBorrarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarSalidaActionPerformed

    private void txfCantidadAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCantidadAlimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCantidadAlimentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<uvpavicol.clases.Lote> boxLotes;
    private javax.swing.JComboBox<uvpavicol.clases.Lote> boxLotesSalida;
    private javax.swing.JComboBox<uvpavicol.clases.TipoAlimento> boxTipoAlimento;
    private javax.swing.JButton btnBorrarDiario;
    private javax.swing.JButton btnBorrarSalida;
    private javax.swing.JButton btnGuardarDiario;
    private javax.swing.JButton btnGuardarSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLotes;
    private javax.swing.JTextField txfAvesSacrificar;
    private javax.swing.JTextField txfCantidadAlimento;
    private javax.swing.JTextField txfMuertes;
    private javax.swing.JTextField txfPesoMedio;
    // End of variables declaration//GEN-END:variables

    
    public class LoteComboBoxModel implements ComboBoxModel<Lote> {
        private Object selected= null;// Objeto seleccionado en el JComboBox
        private Empresa empresa;
        
        //@Override
        public  LoteComboBoxModel(Empresa empresa) {
           this.empresa=empresa;//tipo objeto que recibe
        }
        
        @Override
        public void setSelectedItem(Object item) {
            this.selected = item;//seleccionar item
        }
        @Override
        public int getSize() {
            return empresa.getLosLotes().size();
        }
        @Override
        public Lote getElementAt(int index) {
            return empresa.getLosLotes().get(index);
        }
        @Override
        public Object getSelectedItem() {
            return this.selected;
        }
        @Override
        public void addListDataListener(ListDataListener l) {}
        @Override
        public void removeListDataListener(ListDataListener l) {}
    }
    
    public class LoteInfoModel extends AbstractTableModel{
        @Override
        public int getRowCount() {
            return empresa.getLosLotes().size();
        }

        @Override
        public int getColumnCount() {
            return 2;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Lote loteParaTabla = empresa.getLosLotes().get(rowIndex);
            switch (columnIndex) {
                case 0: return loteParaTabla.getGalpon().getIdentificador();
                case 1: return loteParaTabla.getIdentificador();
                default:
                    throw new AssertionError();
            }
        }
        @Override
        public String getColumnName(int column) {
            switch (column) {
                case 0:return " galpon";
                case 1: return "identificador lote";
            }
            return "reza pq nc, como se ejecutaria esto";
        
        }
    }
    
    public class ManejadorBorrarRegistroDiario implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            txfCantidadAlimento.setText("");
            txfMuertes.setText("");
            txfPesoMedio.setText("");
        }
    }
    public class ManejadorRegistrosDiario implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                Lote lote = (Lote) boxLotes.getSelectedItem();
            
                LocalDate fecha =  LocalDate.now();
                float cantidadAlimento = Float.parseFloat(txfCantidadAlimento.getText());
                int avesMuertas = Integer.parseInt(txfMuertes.getText());
                double pesoPromedio = Double.parseDouble(txfPesoMedio.getText());
                TipoAlimento tipoAlimento = (TipoAlimento) boxTipoAlimento.getSelectedItem();

                RegistroDiario diario= new RegistroDiario(fecha,cantidadAlimento,tipoAlimento,avesMuertas,pesoPromedio);
            
                lote.addRegistroDiario(diario);
            
                tblLotes.updateUI();
                JOptionPane.showMessageDialog(PlantillaGestionLotes.this,"Se guardo Registro");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(PlantillaGestionLotes.this,ex.getMessage());
            }
        }
    }
    
    public class ManejadorBorrarSalidas implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            txfAvesSacrificar.setText("");
            boxLotesSalida.setSelectedItem(null);
        }
    }
    public class ManejadorRegistrosSalidas implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                Lote lote = (Lote) boxLotesSalida.getSelectedItem();
                
                long avesSacrificadas = Long.parseLong(txfAvesSacrificar.getText());
                LocalDate fecha = LocalDate.now();
                LocalTime hora = LocalTime.now();
                long avesVivas = lote.diferenciaAves();
                
                Salida salida = new Salida(avesSacrificadas, fecha, hora,avesVivas);
                
                lote.addSalidas(salida);
                JOptionPane.showMessageDialog(PlantillaGestionLotes.this,"Se Registro Salida Aves");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(PlantillaGestionLotes.this,ex.getMessage());  
            }
        }
    }

}
